
POST http://localhost:5000/project/f4a750b8-8b04-4b3d-a9c5-297ba99c15b4/accept
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjZkM2Y2YmY0LTUxYjMtNGI0MC05MDg0LTk0YWVjZDZjYWMzZCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NuZHJ1YWltbXZvY2F3dmp3cXpmLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyNmYxYTYyOS0yYWVhLTQ5MGMtODQ0Ny03NTg4MDYyMzI2YzkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc2OTQ4ODczLCJpYXQiOjE3NzY5NDUyNzMsImVtYWlsIjoicHJhaXNlaXRvZG81N0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImJpbyI6IkRldmVsb3BlciIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiUHJhaXNlIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzY5NDUyNzN9XSwic2Vzc2lvbl9pZCI6IjEwZTg2M2VhLTJjNGMtNDkwZS05NmE1LWI4OWUyZjkzZjhmMyIsImlzX2Fub255bW91cyI6ZmFsc2V9.JEGW-uwks7Cz3b7k5ckq5f5ZBGbvkq0J6J_wUxCmagAX_oAJGBbNpZ5s7zLUqAPjbDwBkyWBlXEPVxVG67-usQ
Content-Type: application/json

{ "token": "a8db79f1-8f26-4226-a418-4bcdfdec87f5"}