POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjZkM2Y2YmY0LTUxYjMtNGI0MC05MDg0LTk0YWVjZDZjYWMzZCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NuZHJ1YWltbXZvY2F3dmp3cXpmLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyNmYxYTYyOS0yYWVhLTQ5MGMtODQ0Ny03NTg4MDYyMzI2YzkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzczNTUzMzYxLCJpYXQiOjE3NzM1NDk3NjEsImVtYWlsIjoicHJhaXNlaXRvZG81N0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImJpbyI6IkRldmVsb3BlciIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiUHJhaXNlIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzM1NDk2NjV9XSwic2Vzc2lvbl9pZCI6Ijk5ZGVmZmY1LWQ5ZTktNDFiYS05NzAxLTg5MjI2ZmZjYWYyYyIsImlzX2Fub255bW91cyI6ZmFsc2V9._8vhb2RWIoNQMdE3sMDMCO1SXJZXxOrL0EBmnxE_daYJOgsztWFlKRFWqAtIAl_Xr-1QRnVAvSx9V6k3z7B4HQ
