
GET http://localhost:5000/user/profile
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjZkM2Y2YmY0LTUxYjMtNGI0MC05MDg0LTk0YWVjZDZjYWMzZCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NuZHJ1YWltbXZvY2F3dmp3cXpmLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyNmYxYTYyOS0yYWVhLTQ5MGMtODQ0Ny03NTg4MDYyMzI2YzkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzczOTk5NzI0LCJpYXQiOjE3NzM5OTYxMjQsImVtYWlsIjoicHJhaXNlaXRvZG81N0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImJpbyI6IkRldmVsb3BlciIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiUHJhaXNlIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzM5OTYxMjR9XSwic2Vzc2lvbl9pZCI6IjU0MDBhMTRjLTM0NGYtNDQzZS1hMzYyLWVmYzFmZjk1NTViZSIsImlzX2Fub255bW91cyI6ZmFsc2V9.sbz3nKwJ_ywKB2NCiEVCetU7pF024uUnDA8soKljMGiYrKyAjK9OylNXwfcdgEvmUW_bPQZVVTaUG7lHTSUuEQ
